//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationName.Databases.MySql.AppDatabase.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesYahooFinance {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesYahooFinance() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApplicationName.Databases.MySql.AppDatabase.Resources.ResourcesYahooFinance", typeof(ResourcesYahooFinance).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Adj Close,Volume
        ///2021-07-19,15420.139648,15423.839844,15048.559570,15133.200195,15133.200195,85990500
        ///2021-07-20,15234.849609,15300.290039,15091.900391,15216.269531,15216.269531,60029200
        ///2021-07-21,15239.919922,15443.759766,15194.540039,15422.500000,15422.500000,65073800
        ///2021-07-22,15533.219727,15578.750000,15471.469727,15514.540039,15514.540039,50331400
        ///2021-07-23,15603.690430,15681.410156,15583.650391,15669.290039,15669.290039,54897600
        ///2021-07-26,15586.660156,15641.610352,15544.94 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GDAXI_Daily {
            get {
                return ResourceManager.GetString("GDAXI_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Adj Close,Volume
        ///2021-08-01,15631.700195,16030.330078,15492.580078,15835.089844,15835.089844,1034321500
        ///2021-09-01,15958.410156,15981.700195,15019.490234,15260.690430,15260.690430,1337021100
        ///2021-10-01,15041.599609,15781.000000,14818.709961,15688.769531,15688.769531,1349471100
        ///2021-11-01,15764.549805,16290.190430,15015.419922,15100.129883,15100.129883,1635891100
        ///2021-12-01,15233.370117,15974.790039,15060.099609,15884.860352,15884.860352,1354128600
        ///2022-01-01,15947.440430,16285.34960 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GDAXI_Monthly {
            get {
                return ResourceManager.GetString("GDAXI_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Adj Close,Volume
        ///2021-07-19,15420.139648,15681.410156,15048.559570,15669.290039,15669.290039,316322500
        ///2021-07-26,15586.660156,15659.219727,15423.559570,15544.389648,15544.389648,252197700
        ///2021-08-02,15631.700195,15808.240234,15492.580078,15761.450195,15761.450195,272429600
        ///2021-08-09,15773.509766,16030.330078,15699.269531,15977.440430,15977.440430,219121600
        ///2021-08-16,15875.700195,15969.849609,15621.980469,15808.040039,15808.040039,250473300
        ///2021-08-23,15930.719727,15932.620117,157 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GDAXI_Weekly {
            get {
                return ResourceManager.GetString("GDAXI_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Adj Close,Volume
        ///2021-07-19,14235.980469,14313.599609,14178.660156,14274.980469,14274.980469,4507040000
        ///2021-07-20,14330.459961,14555.750000,14271.230469,14498.879883,14498.879883,4618980000
        ///2021-07-21,14508.750000,14633.139648,14498.650391,14631.950195,14631.950195,4075150000
        ///2021-07-22,14652.719727,14694.190430,14617.870117,14684.599609,14684.599609,3574560000
        ///2021-07-23,14753.059570,14846.059570,14698.769531,14836.990234,14836.990234,3959410000
        ///2021-07-26,14821.030273,14863.65039 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IXIC_Daily {
            get {
                return ResourceManager.GetString("IXIC_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Adj Close,Volume
        ///2021-08-01,14758.599609,15288.080078,14423.160156,15259.240234,15259.240234,87630170000
        ///2021-09-01,15308.980469,15403.440430,14444.299805,14448.580078,14448.580078,94713820000
        ///2021-10-01,14494.929688,15504.120117,14181.690430,15498.389648,15498.389648,98654030000
        ///2021-11-01,15541.259766,16212.230469,15451.389648,15537.690430,15537.690430,108529440000
        ///2021-12-01,15752.269531,15901.469727,14860.040039,15644.969727,15644.969727,103643460000
        ///2022-01-01,15732.500000,1585 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IXIC_Monthly {
            get {
                return ResourceManager.GetString("IXIC_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Adj Close,Volume
        ///2021-07-19,14235.980469,14846.059570,14178.660156,14836.990234,14836.990234,20735140000
        ///2021-07-26,14821.030273,14863.650391,14503.759766,14672.679688,14672.679688,20478690000
        ///2021-08-02,14758.599609,14896.469727,14584.089844,14835.759766,14835.759766,20421490000
        ///2021-08-09,14855.759766,14894.610352,14692.410156,14822.900391,14822.900391,20113470000
        ///2021-08-16,14771.530273,14794.679688,14423.160156,14714.660156,14714.660156,19956800000
        ///2021-08-23,14776.980469,15144. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IXIC_Weekly {
            get {
                return ResourceManager.GetString("IXIC_Weekly", resourceCulture);
            }
        }
    }
}
