// <auto-generated />
using ApplicationName.Databases.MySql.AppDatabase.YahooFinanceSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplicationName.Databases.MySql.AppDatabase.YahooFinanceSchema.Migrations
{
    [DbContext(typeof(YahooFinanceAppDatabaseDbContext))]
    [Migration("20220806195459_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);
#pragma warning restore 612, 618
        }
    }
}
