// <auto-generated />
using System;
using ApplicationName.Databases.MySql.AppDatabase.YahooFinanceSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplicationName.Databases.MySql.AppDatabase.YahooFinanceSchema.Migrations
{
    [DbContext(typeof(YahooFinanceAppDatabaseDbContext))]
    [Migration("20220808195106_NasdaqCompositeTables")]
    partial class NasdaqCompositeTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApplicationName.ModelsAndFacilities.EntityModels.YahooFinance.NasdaqComposite.NasdaqCompositeDailyEntityModel", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("Date");

                    b.Property<decimal>("AdjClose")
                        .HasColumnType("decimal(19,9)")
                        .HasColumnName("AdjClose");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(19,9)")
                        .HasColumnName("Close");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(19,9)")
                        .HasColumnName("High");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(19,9)")
                        .HasColumnName("Low");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(19,9)")
                        .HasColumnName("Open");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("Volume");

                    b.HasKey("Date");

                    b.ToTable("nasdaq_composite_daily", (string)null);
                });

            modelBuilder.Entity("ApplicationName.ModelsAndFacilities.EntityModels.YahooFinance.NasdaqComposite.NasdaqCompositeMonthlyEntityModel", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("Date");

                    b.Property<decimal>("AdjClose")
                        .HasColumnType("decimal(19,9)")
                        .HasColumnName("AdjClose");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(19,9)")
                        .HasColumnName("Close");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(19,9)")
                        .HasColumnName("High");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(19,9)")
                        .HasColumnName("Low");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(19,9)")
                        .HasColumnName("Open");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("Volume");

                    b.HasKey("Date");

                    b.ToTable("nasdaq_composite_monthly", (string)null);
                });

            modelBuilder.Entity("ApplicationName.ModelsAndFacilities.EntityModels.YahooFinance.NasdaqComposite.NasdaqCompositeWeeklyEntityModel", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("Date");

                    b.Property<decimal>("AdjClose")
                        .HasColumnType("decimal(19,9)")
                        .HasColumnName("AdjClose");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(19,9)")
                        .HasColumnName("Close");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(19,9)")
                        .HasColumnName("High");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(19,9)")
                        .HasColumnName("Low");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(19,9)")
                        .HasColumnName("Open");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("Volume");

                    b.HasKey("Date");

                    b.ToTable("nasdaq_composite_weekly", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
